# Generated by Django 5.1.1 on 2024-09-14 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998 XX XXX-XX-XX'.", regex='^\\+998 \\d{2} \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
